name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew installDist --parallel

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: steep-build
          path: build
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: steep-build
          path: build

      - name: Run unit tests
        run: ./gradlew test -x :ui:processResources jacocoTestReport

      - name: Upload code coverage report
        run: bash <(curl -s https://codecov.io/bash) -s build/reports/jacoco

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: steep-build
          path: build

      - name: Build Docker image
        run: |
          docker build -t steep/steep .
          docker tag steep/steep steep/steep:unstable

      - name: Push Docker image
        if: github.repository == 'steep-wms/steep' && github.event_name == 'push'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USERNAME --password-stdin
          docker push steep/steep:unstable
